# Copyright 2021, akashche at redhat.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


task:
  matrix:
    container:
      image: ojdkbuild/centos6-jdk8u
      cpu: 2
      memory: 2G

  environment:
    GITHUB_TOKEN: ENCRYPTED[f9fd6575c318132c9cf39e9f8ed5ee53710a425de67925c93b63d177884383a0e3533f2db40b2f32044c049d552c7c66]

  script: |
    set -e
    export OJDK_TAG=`git describe --exact-match --tags HEAD`
    if [ -z ${OJDK_TAG} ] ; then exit 1 ; fi
    export OJDK_UPDATE=`echo ${OJDK_TAG} | sed 's/-/ /' | awk '{print substr($1,6)}'`
    export OJDK_BUILD=`echo ${OJDK_TAG} | sed 's/-/ /' | awk '{print substr($2,2)}'`
    export OJDK_IMAGE=jdk-8u${OJDK_UPDATE}-ojdkbuild-linux-x64
    git clone https://github.com/ojdkbuild/8u282-test.git /jdk8u
    # build
    cd /opt && bash /jdk8u/configure \
            --enable-unlimited-crypto=yes \
            --enable-debug-symbols=no \
            --with-debug-level=release \
            --with-stdc++lib=static \
            --with-boot-jdk=/usr/lib/jvm/java-openjdk \
            --with-cacerts-file=/etc/pki/java/cacerts \
            --with-milestone=fcs \
            --with-update-version=${OJDK_UPDATE} \
            --with-build-number=${OJDK_BUILD} \
            --with-vendor-name=ojdkbuild \
            --with-vendor-url=https://github.com/ojdkbuild \
            --with-vendor-bug-url=https://github.com/ojdkbuild/ojdkbuild/issues \
            --with-vendor-vm-bug-url=https://github.com/ojdkbuild/ojdkbuild/issues
    unset OS
    cd /opt && make images LOG=info
    mv /opt/images/j2sdk-image /opt/${OJDK_IMAGE}
    rm -rf /opt/${OJDK_IMAGE}/demo
    rm -rf /opt/${OJDK_IMAGE}/sample
    cp -a /usr/share/fonts/dejavu/ /opt/${OJDK_IMAGE}/jre/lib/fonts
    cd /opt && zip -qyr9 ${OJDK_IMAGE}.zip ${OJDK_IMAGE}
    mkdir /opt/dist
    mv /opt/${OJDK_IMAGE}.zip /opt/dist/${OJDK_IMAGE}.zip
    cd /opt/dit && sha256sum ${OJDK_IMAGE}.zip > ${OJDK_IMAGE}.zip.sha256
    # deploy
    curl -LO https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
    tar -xzf ghr_v0.13.0_linux_amd64.tar.gz
    ./ghr_v0.13.0_linux_amd64/ghr -t $(GITHUB_TOKEN) -u ojdkbuild -r ojdkbuild -c ${CIRRUS_CHANGE_IN_REPO} ${CIRRUS_TAG} /opt/dist
